fotcamp/Finhub-Backend

src/main/java/fotcamp/finhub/common/config/WebConfig.java

- [o] 🌍 빌드 설정 및 문제
fe local url cors test
- 작업1

:white_check_mark: FE local url cors test

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

:white_check_mark: FE local url cors test #2

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

:white_check_mark: FE local url cors test #3

---

src/main/java/fotcamp/finhub/main/controller/AuthApiController.java

KakaoLogin Hotfix 

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

- [o] 🌍 빌드 설정 및 문제
kakao login url hotfix test
- 작업1

kakao login url hotfix test

---

src/main/java/fotcamp/finhub/common/config/SecurityConfig.java
src/main/java/fotcamp/finhub/common/exception/ErrorMessage.java
src/main/java/fotcamp/finhub/common/security/JwtAuthFilter.java
src/main/java/fotcamp/finhub/common/security/JwtExceptionFilter.java

#24 
- authorization header 키값 null, value값 null일때 분기처리

#24 authorization header 에러 분기처리 (key null, value null)

---

src/main/java/fotcamp/finhub/main/dto/LoginResponseDto.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

#30 
- 로그인 성공시, 액세스토큰, 리프레시토큰 + 사용자 이름, 이메일 정보 반환

#30 로그인 response Dto 수정

---

src/main/generated/fotcamp/finhub/common/domain/QRefreshToken.java
src/main/java/fotcamp/finhub/common/domain/RefreshToken.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/common/exception/NotFoundException.java
src/main/java/fotcamp/finhub/common/security/CustomUserDetailService.java
src/main/java/fotcamp/finhub/common/security/JwtAuthFilter.java
src/main/java/fotcamp/finhub/common/security/JwtExceptionFilter.java
src/main/java/fotcamp/finhub/common/utils/JwtUtil.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/dto/request/AutoLoginRequestDto.java
src/main/java/fotcamp/finhub/main/dto/request/RefreshTokenRequestDto.java
src/main/java/fotcamp/finhub/main/dto/response/AutoLoginResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/LoginResponseDto.java
src/main/java/fotcamp/finhub/main/repository/TokenRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

#35 
- 액토, 리토 request -> 토큰 검증 이후 rt 갱신 및 사용자정보와 함께 at,rt 응답
( 노션 api 에 과정 작성 )

#35 자동로그인 autoLogin 구현

---

src/main/generated/fotcamp/finhub/common/domain/QMemberQuiz.java
src/main/generated/fotcamp/finhub/common/domain/QQuiz.java
src/main/generated/fotcamp/finhub/common/domain/QTopicQuiz.java
src/main/generated/fotcamp/finhub/main/domain/QMember.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateQuizRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/CreateQuizResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/QuizRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicQuizRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/MemberQuiz.java
src/main/java/fotcamp/finhub/common/domain/Quiz.java
src/main/java/fotcamp/finhub/common/domain/TopicQuiz.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/common/utils/DateUtil.java
src/main/java/fotcamp/finhub/main/domain/Member.java

- [o ] 🚀 feature 기능 추가
34
퀴즈 생성 api 개발
- 작업1

:white_check_mark: admin 퀴즈 생성 api 개발

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/GptLogProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/QuizProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/QuizTopicProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateQuizRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/AllGptLogResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/GetDailyQuizResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/GetMonthlyQuizResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/QuizRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java

#34
- 퀴즈 월 전체 조회
- 퀴즈 일 상세 조회
- 작업1

:white_check_mark: admin 퀴즈 월 전체조회/ 일 상세조회 api 개발

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/ModifyQuizRequestDto.java
src/main/java/fotcamp/finhub/admin/repository/TopicQuizRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Quiz.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java

close #34 
- 퀴즈 수정 api 개발
-  pathvariable validation service 단으로 이동

:white_check_mark: admin 퀴즈 수정 / pathvariable validate 수정

---

src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/common/domain/UserType.java

#32 
- 메인 엔티티 user_type 일대다 관계 추가

#32 메인 엔티티 user_type 일대다 관계 추가

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/ModifyBannerRequestDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Banner.java

:white_check_mark: 배너 수정 api 개발

---

src/main/java/fotcamp/finhub/admin/repository/CategoryRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/response/LoginHomeResponseDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

Feature/issue 54 first tab  (스크랩미구현) 첫번째 탭 3가지 기능 구현[온보딩, 다른카테고리택, 더보기]

---

src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/common/domain/PopularSearch.java
src/main/java/fotcamp/finhub/common/domain/RecentSearch.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/response/PopularKeywordResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/RecentSearchResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/SearchResponseDto.java
src/main/java/fotcamp/finhub/main/repository/PopularKeywordRepository.java
src/main/java/fotcamp/finhub/main/repository/RecentSearchRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java
src/test/java/fotcamp/finhub/main/deleteRecentKeyword.java

Feature/issue 63 recent search delete 최근검색어 삭제, 전체삭제

---

src/main/java/fotcamp/finhub/admin/repository/TopicRequestRepository.java
src/main/java/fotcamp/finhub/common/domain/TopicRequest.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/request/NewKeywordRequestDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#65 없는 단어 요청하기 로직 구현

---

src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/DetailNextTopicProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/DetailTopicProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/DetailTopicResponseDto.java
src/main/java/fotcamp/finhub/main/repository/MemberScrapRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#67 토픽상세페이지 (gpt 결합 전)

---

src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#72 스크랩 해제, 아바타 지우기 기능 구현

---

src/main/generated/fotcamp/finhub/common/domain/QMember.java
src/main/generated/fotcamp/finhub/common/domain/QRefreshToken.java
src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/common/domain/RefreshToken.java
src/main/java/fotcamp/finhub/main/repository/TokenRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

#75 리프레시토큰 멤버엔티티 외래키 제약조건

---

src/main/java/fotcamp/finhub/main/dto/process/MyScrapProcessDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#77 나의 스크랩 응답 데이터 추가

---

src/main/generated/fotcamp/finhub/common/domain/QGptColumn.java
src/main/generated/fotcamp/finhub/common/domain/QTopicGptColumn.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/GetGptColumnProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/GptColumnTopicProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateGptColumnRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/ModifyGptColumnRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/SaveGptColumnRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/AllGptColumnResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/DetailGptColumnResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/GptColumnRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicGptColumnRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/GptColumn.java
src/main/java/fotcamp/finhub/common/domain/TopicGptColumn.java

gpt column api 개발 (admin)
close #74 
- 작업1

:white_check_mark: gpt column 생성/수정/조회 api 개발

---

src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#82 서블릿 에러처리

---

src/main/java/fotcamp/finhub/admin/repository/BannerRepository.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/BannerListProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/BannerListResponseDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

close #81 
- 메인 배너 api 개발
- 작업1

:white_check_mark: main 배너 api 개발

---

src/main/java/fotcamp/finhub/main/service/MainService.java

#85 s3 이미지응답 주소 변경

---

src/main/java/fotcamp/finhub/admin/dto/response/AdminLoginResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java

#88 로그인 응답 데이터 추가

---

src/main/java/fotcamp/finhub/admin/repository/GptColumnRepository.java
src/main/java/fotcamp/finhub/admin/repository/UserTypeRepository.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/SearchColumnResultListProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/SearchTopicResultListProcessDto.java
src/main/java/fotcamp/finhub/main/dto/request/SelectJobRequestDto.java
src/main/java/fotcamp/finhub/main/dto/response/SearchColumnResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/SearchTopicResponseDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#51 컬럼 주제,내용, 주제+내용 검색 기능

---

src/main/java/fotcamp/finhub/main/dto/process/DetailTopicProcessDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#104 토픽상세 응답 메시지 수정 - 요약 누락 건

---

src/main/java/fotcamp/finhub/common/dto/response/ErrorMessageResponseDto.java
src/main/java/fotcamp/finhub/main/dto/process/DetailTopicProcessDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#106 에러 응답 메시지 포맷 통일 작업

---

src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/thirdTab/SearchColumnResultListProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/thirdTab/SearchPageInfoProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/thirdTab/SearchTopicResultListProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/RecentSearchResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/SearchColumnResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/SearchTopicResponseDto.java
src/main/java/fotcamp/finhub/main/repository/RecentSearchRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#108 검색 기능 코드 리팩토링 & api 명 변경

---

src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/common/domain/Topic.java
src/main/java/fotcamp/finhub/main/controller/QuizController.java
src/main/java/fotcamp/finhub/main/dto/response/quiz/CalendarQuizResponseDto.java
src/main/java/fotcamp/finhub/main/dto/response/quiz/EmoticonDto.java
src/main/java/fotcamp/finhub/main/dto/response/quiz/EmoticonSaveRequestDto.java
src/main/java/fotcamp/finhub/main/service/QuizService.java

:white_check_mark: 달력 이모티콘 저장 api 개발

---

src/main/java/fotcamp/finhub/admin/dto/request/ModifyTopicRequestDto.java

:white_check_mark: 토픽 수정 api 수정

---

.gitignore
build.gradle
src/main/generated/fotcamp/finhub/common/domain/QMember.java
src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/common/exception/FcmException.java
src/main/java/fotcamp/finhub/main/config/FcmConfig.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/controller/FcmController.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/FcmMessageProcessDto.java
src/main/java/fotcamp/finhub/main/dto/request/FcmMessageRequestDto.java
src/main/java/fotcamp/finhub/main/dto/request/FcmTokenRequestDto.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService.java
src/main/java/fotcamp/finhub/main/service/FcmService.java

#17 fcm setting 구현

---

.github/workflows/gradle.yml

:white_check_mark: fcm json 파일 추가

---

src/main/java/fotcamp/finhub/main/config/FcmConfig.java

임시 FcmConfig 주석처리

---

src/main/java/fotcamp/finhub/admin/domain/GptLog.java

:white_check_mark: gptlog answer 형식 변경

---

.github/workflows/gradle.yml

:white_check_mark: gradle.yml 수정

---

src/main/java/fotcamp/finhub/main/controller/AuthApiController.java

#17 자동로그인 http method 수정

---

.github/workflows/gradle.yml

Chore: Add workflow slack message

---

src/main/java/fotcamp/finhub/admin/repository/CategoryRepository.java
src/main/java/fotcamp/finhub/admin/repository/GptColumnRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/admin/repository/UserAvatarRepository.java
src/main/java/fotcamp/finhub/admin/repository/UserTypeRepository.java
src/main/java/fotcamp/finhub/main/dto/process/secondTab/DetailNextTopicProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/secondTab/DetailTopicProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/secondTab/TopicListProcessDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#127 Topic img_url 응답데이터 추가 및 UseYN필터 작업

---

src/main/java/fotcamp/finhub/common/domain/MemberGptColumn.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/MyScrapColumnProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/MyScrapTopicProcessDto.java
src/main/java/fotcamp/finhub/main/repository/MemberGptColumnRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#129 기존 스크랩 모음 api (토픽, 컬럼 구분) 리팩토링

---

src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

#132 자동로그인 api 리팩토링, fcm token 업데이트 api

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateAnnounceRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteAnnounceRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/ModifyAnnounceRequestDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Announcement.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/AnnouncementProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/AnnouncementResponseDto.java
src/main/java/fotcamp/finhub/main/repository/AnnouncementRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService.java
src/main/java/fotcamp/finhub/main/service/MainService.java

공지사항 admin api(생성,수정,삭제), main api (조회) 구현

---

src/main/generated/fotcamp/finhub/common/domain/QCommentsReport.java
src/main/generated/fotcamp/finhub/common/domain/QReportReasons.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/ReportReasonModifyRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/ReportReasonRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/ReportReasonsAnswerDto.java
src/main/java/fotcamp/finhub/admin/dto/response/ReportReasonsDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/CommentsReport.java
src/main/java/fotcamp/finhub/common/domain/ReportReasons.java
src/main/java/fotcamp/finhub/main/controller/ColumnController.java
src/main/java/fotcamp/finhub/main/dto/response/column/CommentReportRequestDto.java
src/main/java/fotcamp/finhub/main/dto/response/column/ReportReasonAnswerDto.java
src/main/java/fotcamp/finhub/main/dto/response/column/ReportReasonListDto.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepository.java
src/main/java/fotcamp/finhub/main/repository/ReportReasonsRepository.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java

2024.04.20 비정기반영

---

src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteCategoryRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteTopicRequestDto.java
src/main/java/fotcamp/finhub/admin/repository/GptRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicGptColumnRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicQuizRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/common/domain/Category.java
src/main/java/fotcamp/finhub/common/domain/Gpt.java
src/main/java/fotcamp/finhub/common/domain/MemberScrap.java
src/main/java/fotcamp/finhub/common/domain/Topic.java
src/main/java/fotcamp/finhub/common/domain/TopicGptColumn.java
src/main/java/fotcamp/finhub/common/domain/TopicQuiz.java
src/main/java/fotcamp/finhub/main/repository/MemberScrapRepository.java

#142 삭제 테스트 진행중

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java

:white_check_mark: 에러 수정 test

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepository.java
src/main/java/fotcamp/finhub/admin/repository/GptRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicGptColumnRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/dto/process/AnnouncementProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/AnnouncementResponseDto.java
src/main/java/fotcamp/finhub/main/repository/AnnouncementRepository.java
src/main/java/fotcamp/finhub/main/repository/MemberScrapRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#142 admin delete 메소드 (카테고리, 토픽 구현) , 공지사항 조회 api 추가

---

src/main/java/fotcamp/finhub/main/config/KakaoConfig.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

:white_check_mark: 카카오 로그인 로컬/개발 분기 추가

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteUsertypeRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/DetailAnnounceResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java

#158 ADMIN 공지사항 상세페이지

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteUsertypeRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/DetailAnnounceResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/config/SwaggerConfig.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/controller/ColumnController.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/controller/QuizController.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService.java

swagger 설정 + kakao redirect uri 분기처리

---

src/main/generated/fotcamp/finhub/common/domain/QCommentsReport.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/domain/Manager.java
src/main/java/fotcamp/finhub/admin/repository/TopicRequestRepositoryCustom.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Comments.java
src/main/java/fotcamp/finhub/common/domain/CommentsReport.java
src/main/java/fotcamp/finhub/main/dto/process/ReportedCommentsProcessDto.java
src/main/java/fotcamp/finhub/main/dto/response/column/ReportCommentRequestDto.java
src/main/java/fotcamp/finhub/main/dto/response/column/ReportedCommentsResponseDto.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepositoryCustom.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepositoryImpl.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java
src/test/java/fotcamp/finhub/admin/repository/AdminLoginTest.java

신고 댓글 처기 api 반영

---

src/main/java/fotcamp/finhub/common/config/SwaggerConfig.java

:white_check_mark: 운영 swagger 설정

---

src/main/java/fotcamp/finhub/common/config/SecurityConfig.java

:white_check_mark: 운영 swagger test

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/response/DetailGptColumnResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/dto/response/column/AdminCommentResponseDto.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java

:white_check_mark: admin gpt column 상세 댓글 추가

---

.gitignore
src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/main/dto/process/thirdTab/SearchTopicResultListProcessDto.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#175 프론트요청 - 검색 응답데이터 카테고리id추가

---

src/main/java/fotcamp/finhub/admin/repository/MemberQuizRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/controller/QuizController.java
src/main/java/fotcamp/finhub/main/dto/process/ReportedCommentsProcessDto.java
src/main/java/fotcamp/finhub/main/service/QuizService.java

20240511 비정기반영

---

.github/workflows/pr_approve.yml
.github/workflows/pr_review.yml

Add pr review slack bots
- pr review bot
- pr approve bot

chore: Add pr review slack bots

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

#190 CORS PATCH 메서드 추가

---

src/main/java/fotcamp/finhub/admin/service/FcmService.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/dto/process/FcmMessageProcessDto.java

#195 fcm message notification 필드추가

---

src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteCalendarEmojiRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteReportReasonRequestDto.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/admin/service/FcmService.java
src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/common/exception/ErrorMessage.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/dto/process/FcmMessageProcessDto.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java

20240522 비정기반영

---

src/main/java/fotcamp/finhub/admin/dto/process/TopicIdTitleDto.java
src/main/java/fotcamp/finhub/main/controller/QuizController.java

:white_check_mark: 퀴즈 api 응답 스펙 변경(category, topic Id 추가)

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java

:white_check_mark: gpt 요약 생성 title로 생성하게끔 변경

---

src/main/java/fotcamp/finhub/admin/service/FcmService.java

#204 fcm service 예외 에러 디버깅

---

src/main/java/fotcamp/finhub/main/repository/WeekPopularKeywordRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

:white_check_mark: 인기검색어 최신날짜 데이터만 가져오기

---

src/main/generated/fotcamp/finhub/common/domain/QBlock.java
src/main/java/fotcamp/finhub/common/domain/Block.java
src/main/java/fotcamp/finhub/main/controller/ColumnController.java
src/main/java/fotcamp/finhub/main/dto/request/BlockMemberRequestDto.java
src/main/java/fotcamp/finhub/main/repository/BlockRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java

컬럼) 사용자 차단 기능, 차단 멤버 제외한 컬럼 댓글 조회

---

src/main/generated/fotcamp/finhub/common/domain/QBlock.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateFcmMessageRequestDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/admin/service/FcmService.java
src/main/java/fotcamp/finhub/common/domain/Block.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/controller/ColumnController.java
src/main/java/fotcamp/finhub/main/dto/process/FcmMessageProcessDto.java
src/main/java/fotcamp/finhub/main/dto/request/BlockMemberRequestDto.java
src/main/java/fotcamp/finhub/main/repository/BlockRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java

#213 공지사항 새로 생성시, 전체 관리자 및 멤버에게 푸시알림 전송

---

src/main/generated/fotcamp/finhub/common/domain/QCategory.java
src/main/generated/fotcamp/finhub/common/domain/QTopic.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/AllCategoryProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/TopicProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/OrderRequestDto.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepository.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Category.java
src/main/java/fotcamp/finhub/common/domain/Topic.java
src/main/java/fotcamp/finhub/common/utils/PageableUtil.java
src/main/java/fotcamp/finhub/main/repository/WeekPopularKeywordRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

36번 이슈 처리
admin 카테고리, 토픽 순서 지정
main 카테고리, 토픽 순서에 맞게 select
- 작업1

:white_check_mark: admin 카테고리, 토픽 순서 지정. main 순서에 맞게 조회

---

src/main/java/fotcamp/finhub/main/repository/BlockRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java

#219 
- 쿼리 날릴 때 @Param을 안써서 결과문을 안가져오는 것 같습니다. 로컬 테스트 확인 완료

#218 차단 멤버 리스트 조회 메소드 수정

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepositoryImpl.java

:white_check_mark: admin 카테고리, 토픽 순서 null이 정렬 시 앞으로 가게끔 수정

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/response/AllCategoryResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/AllTopicResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java

:white_check_mark: admin 카테고리, 토픽 전체조회 페이징 제거

---

src/main/java/fotcamp/finhub/admin/dto/process/TopicProcessDto.java

:white_check_mark: admin 토픽전체조회 응답 스펙 변경(topicId -> id)

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/TopicProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/response/AllCategoryResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/AllTopicResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepository.java
src/main/java/fotcamp/finhub/admin/repository/CategoryRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/admin/repository/TopicRepositoryImpl.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java

20240610 비정기반영

---

src/main/java/fotcamp/finhub/main/dto/process/MyCommentsListProcessDto.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#233 내 댓글 몰아보기 필터링 수정 및 응답데이터 수정(컬럼id, 날짜)

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/Gpt.java

내 댓글 몰아보기 api 수정

---

build.gradle
src/main/java/fotcamp/finhub/common/security/JwtExceptionFilter.java
src/main/java/fotcamp/finhub/test/TestController.java
src/main/webapp/WEB-INF/views/home.jsp

:white_check_mark: 카카오 지도 api 테스트

---

src/main/java/fotcamp/finhub/admin/repository/TopicRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#237 다음 토픽 확인 api 리팩토링(position 기준 오름차순)

---

src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/repository/BlockRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsLikeRepository.java
src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#241 회원탈퇴 코드 리팩토링 (cascade 지양, 관련 레코드 검색해 삭제하는 방향으로)

---

src/main/java/fotcamp/finhub/main/service/MainService.java

#244 직업선택 API 코드 리팩토링 - 0번 ID : 선택없음(NULL)

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateFcmMessageRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/FcmResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/ManagerRepository.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/admin/service/FcmService.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepository.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#247 
- FCM 요청 API 요청, 응답 포맷 변경 - 로컬 테스트 진행 완료
- 코드 리팩토링
- 쿼리 최적화 진행

#247 FCM 푸시 API 요청, 응답 포맷 변경, 코드 리팩토링

---

src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/dto/request/DeleteBannerRequestDto.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java

#242 
- ADMIN 페이지 배너 삭제 API
로컬 테스트 완료

#242 ADMIN 배너 삭제 API

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

#259 CORS 포트 추가

---

src/main/java/fotcamp/finhub/main/repository/MemberNotificationRepository.java
src/main/java/fotcamp/finhub/main/repository/PostsLikeRepository.java
src/main/java/fotcamp/finhub/main/service/MainService.java

회원탈퇴 디버깅, 알람 목록 응답 데이터 리팩토링

---

src/main/java/fotcamp/finhub/main/repository/MemberNotificationRepository.java

#265 알람 목록 api 쿼리 리팩토링 (읽은 알람 커서 id 이상시, 안보이는 문제 해결)

---

src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

#270 deploy 에러 해결 테스트 (기존 파일 삭제 후 동일이름 재생성으로 인한 컴파일과 런타임 클래스 차이 발생 추정)

---

src/main/java/fotcamp/finhub/main/config/OAuth2Util.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java

#273 구글 로그인 배포URL 스웨거 명시

---

src/main/java/fotcamp/finhub/main/config/OAuth2Util.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

2024.07.25 비정기반영

---

src/main/java/fotcamp/finhub/common/domain/Member.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/service/MainService.java

#278 
- 멤버 테이블 fcm 토큰 정보 공백처리 api

#278 fcm token 공백처리 api

---

src/main/java/fotcamp/finhub/main/service/MainService.java

#178 멤버 테이블 FCM 토큰 정보 공백처리 API

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/common/config/WebConfig.java

2024.07.29 비정기반영

---

src/main/java/fotcamp/finhub/common/config/WebConfig.java

:white_check_mark: WebConfig 수정

---

src/main/java/fotcamp/finhub/main/config/AppleJwtConfig.java
src/main/java/fotcamp/finhub/main/config/OAuth2Util.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

#276 애플 로그인 개발 (4)

---

src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/common/domain/Comments.java
src/main/java/fotcamp/finhub/main/repository/CommentsLikeRepository.java

#296 
- 컬럼 삭제 전 댓글 목록, 댓글좋아요 목록 데이터 삭제

#296 어드민 컬럼 삭제하기 api 디버깅 (댓글 좋아요 목록, 댓글 삭제 )

---

src/main/generated/fotcamp/finhub/common/domain/QAgreement.java
src/main/generated/fotcamp/finhub/common/domain/QFeedback.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/common/domain/Agreement.java
src/main/java/fotcamp/finhub/common/domain/Comments.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/dto/request/SignUpAgreeRequest.java
src/main/java/fotcamp/finhub/main/repository/CommentsLikeRepository.java
src/main/java/fotcamp/finhub/main/repository/SignUpAgreementRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

#294 회원가입 이용 약관 동의 API 개발

---

src/main/java/fotcamp/finhub/main/service/MainService.java

#298 스크랩 모음 (컬럼 ID 미일치 해결 )

---

src/main/java/fotcamp/finhub/main/service/MainService.java

#304 
- Comment table 레코드 삭제 전 CommentLike table 레코드 먼저 물리삭제 진행.

#304 회원탈퇴 API - 댓글 테이블 레코드 삭제 전, 댓글 좋아요 레코드 선 삭제 과정으로 수정

---

build.gradle
src/main/generated/fotcamp/finhub/common/domain/QFeedback.java
src/main/java/fotcamp/finhub/FinhubApplication.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/VocDetailProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/VocListProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/VocProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/ReplyRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/SaveImgToS3RequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocDetailResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocListResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/admin/service/EmailService.java
src/main/java/fotcamp/finhub/common/domain/Feedback.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/common/service/AwsS3Service.java
src/main/java/fotcamp/finhub/common/service/SlackWebhookService.java
src/main/java/fotcamp/finhub/common/utils/JwtUtil.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/request/FeedbackRequestDto.java
src/main/java/fotcamp/finhub/main/repository/FeedbackRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java
src/main/java/fotcamp/finhub/main/service/MainService.java
src/main/java/fotcamp/finhub/main/service/QuizService.java

메인 서비스 : 요청사항 api ( 로그인 유저는 알람 전송, 비로그인 유저는 알람x)
어드민 서비스 :  voc 목록 전체 조회(페이징), 요청사항 응답 메일 전송 api 구현
#277 
- noreply 이메일 작업은 미진행
- 이미지 업로드시에만 s3 base url 활용, 나머진 cdn으로 전환
-

voc admin, main 서비스 테스트 진행 완료, CloudFront URL로 baseurl 변경작업 완료

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/repository/CommentsReportRepository.java

- 댓글신고내역이 다건인 경우를 고려하여 단건조회검증 -> exists 검증 방식으로 교체
- 댓글신고내역이 다건인 경우를 고려하여 단건조회검증 -> exists 검증 방식으로 교체
- 추후 QueryDsl 방식의 조회로 변경 고려 중
- command와 query를 분리하는 설계패턴에 대한 논의

#127 BE) 어드민 컬럼 id 7 500 에러

---

build.gradle
src/main/generated/fotcamp/finhub/common/domain/QFeedback.java
src/main/java/fotcamp/finhub/FinhubApplication.java
src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/VocDetailProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/VocListProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/process/VocProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/ReplyRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/request/SaveImgToS3RequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocDetailResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocListResponseDto.java
src/main/java/fotcamp/finhub/admin/dto/response/VocResponseDto.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/admin/service/EmailService.java
src/main/java/fotcamp/finhub/common/domain/Feedback.java
src/main/java/fotcamp/finhub/common/exception/ExceptionController.java
src/main/java/fotcamp/finhub/common/service/AwsS3Service.java
src/main/java/fotcamp/finhub/common/service/SlackWebhookService.java
src/main/java/fotcamp/finhub/common/utils/JwtUtil.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/process/MyScrapColumnProcessDto.java
src/main/java/fotcamp/finhub/main/dto/process/MyScrapTopicProcessDto.java
src/main/java/fotcamp/finhub/main/dto/request/FeedbackRequestDto.java
src/main/java/fotcamp/finhub/main/repository/FeedbackRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java
src/main/java/fotcamp/finhub/main/service/MainService.java
src/main/java/fotcamp/finhub/main/service/QuizService.java

#277 
- VOC API 작업 완료
- 회원탈퇴 디버깅

Refactor/issue 277 voc2 -> Dev branch

---

src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/dto/process/login/UserInfoProcessDto.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

#311 
- 소셜 로그인시, 신규회원 기존회원 유무 판별 필드 추가

#311 소셜 로그인시, 신규회원 유무 판별 필드 추가

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java

#313 관리자 VOC 답변 프로세스 수정 ( DB업데이트 이후 이메일 전송 )

---

.github/workflows/pr_merged.yml

merged slack 알림 추가
close #315 
- github action yml 작성

chore: add pr_merged slack notify

---

src/main/java/fotcamp/finhub/main/repository/CommentsRepository.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java

#323 
- [작업1](https://fin-hub.atlassian.net/jira/software/projects/FIN/list?direction=DESC&filter=%22status%22%20in%20%28%27Back-log%27%2C%27OPEN%E2%98%85%27%2C%27TESTED%27%2C%27RESOLVED%E2%98%85%27%2C%27RFI%27%29&selectedIssue=FIN-115&sortBy=priority)
- 최신순, 인기순 응답데이터 뒤바뀜 해결

#323 컬럼 의견 나누기 API - 최신순 인기순 응답 데이터 뒤바뀜 해결

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

#331 
- 헤더에 "Bearer xxxxxxxxxx" 토큰 정보 인자가 메소드로 그대로 전달되어서 에러 발생
- "Bearer " 파싱 후 토큰정보만 전달하는 것으로 디버깅

#331 자동로그인 API - 액세스토큰 파싱 디버깅

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/CommentsReport.java
src/main/java/fotcamp/finhub/main/dto/process/ReportedCommentsProcessDto.java

- 댓글 신고 시, 댓글 신고관리 엔티티의 useYn값 => Y 처리
- 댓글신고내역조회 시, 댓글 신고관리 엔티티의 useYn값 반환하도록 수정
- 작업1

#131 Admin) 칼럼 댓글 관리

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

- workflow 파일에서 mkdir 명령어에 -p 옵션 추가하여 경로가 이미 존재할 경우 예외처리
- 작업1

[131] Admin) 칼럼 댓글 관리 #5

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/dto/process/FcmMemberInfoProcessDto.java
src/main/java/fotcamp/finhub/admin/dto/request/CreateFcmMessageRequestDto.java
src/main/java/fotcamp/finhub/admin/dto/response/FcmMemberInfoListResponseDto.java
src/main/java/fotcamp/finhub/admin/repository/ManagerRepository.java
src/main/java/fotcamp/finhub/admin/service/FcmService.java
src/main/java/fotcamp/finhub/main/repository/AgreementRepository.java
src/main/java/fotcamp/finhub/main/repository/MemberRepository.java

- EMAIL -> UUID 로 타겟 선별
- 전송대상 목록 조회 API 개발
지라 142번 이슈에 스크린샷 기재

ADMIN) FCM 푸시 알림 전송 리팩토링 (EMAIL -> UUID) & 푸시알림 대상 목록 조회 API 개발 

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/admin/service/EmailService.java

[160] ADMIN) VOC 답변 메일 본문 내용 수정 

---

.github/workflows/ci.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

CI 테스트 & github action job 실행 버튼 추가
- CI 테스트
develop, main으로 PR올리시면 미리 build를 시켜서(CI) 빌드 여부를 확인합니다
- github action job 실행 버튼 추가
1) repository > action으로 들어갑니다.
2) trigger할 수 있는 버튼을 클릭합니다(re run job없이 실행가능합니다)

CI 테스트 & github action job 실행 버튼 추가

---

Dockerfile

- 컨테이너 내부 시간대 설정을 위한 tzdata 설치 스크립트 로직 추가
- 작업1

[168] 로그 모니터링 시스템 구축 #1

---

src/main/generated/fotcamp/finhub/common/domain/QMemberAgreement.java
src/main/java/fotcamp/finhub/common/domain/MemberAgreement.java
src/main/java/fotcamp/finhub/main/controller/AuthApiController.java
src/main/java/fotcamp/finhub/main/repository/AgreementRepository.java
src/main/java/fotcamp/finhub/main/service/AuthService2.java

- 멤버 생성 이후 신규회원에서 기존회원으로 변경하는 프로세스 개선
- 약관 동의를 마친 이후 기존회원으로 상태 변경 과정 개발
- 작업1

[165] AUTH) 신규회원 상태 변경 이슈 #1

---

Dockerfile

- 컨테이너 내부에 로그파일 저장을 위한 별도 경로 생성하도록 도커파일 수정
- 작업1

[169] 로그 모니터링 시스템 구축

---

src/main/java/fotcamp/finhub/admin/controller/AdminController.java
src/main/java/fotcamp/finhub/admin/controller/AdminDeleteController.java
src/main/java/fotcamp/finhub/admin/service/AdminDeleteService.java
src/main/java/fotcamp/finhub/admin/service/AdminService.java
src/main/java/fotcamp/finhub/common/domain/MemberAgreement.java
src/main/java/fotcamp/finhub/main/controller/ColumnController.java
src/main/java/fotcamp/finhub/main/controller/MainController.java
src/main/java/fotcamp/finhub/main/dto/request/ScrapRequestDto.java
src/main/java/fotcamp/finhub/main/service/ColumnService.java
src/main/java/fotcamp/finhub/main/service/MainService.java

- “단어” → “ 토픽”
- “아티클”, “컬럼”
- “GPT컬럼” → “GPT 칼럼”
- 작업1

[149] 워딩 수정 요청

---

Dockerfile
src/main/resources/logback-spring.xml

This reverts commit 3ec68ec4e9270841eacdb2b7fa4f349dc83b1833.
- 작업1

Revert "Revert "[169] 로그 모니터링 시스템 구축""

---

src/main/java/fotcamp/finhub/admin/service/AdminService.java

- 승인, 반려에따라 댓글 사용여부 상태 분기처리
- 작업1

[131] Admin) 칼럼 댓글 관리

---

src/main/java/fotcamp/finhub/common/security/JwtAuthFilter.java
src/main/java/fotcamp/finhub/common/security/JwtExceptionFilter.java
src/main/java/fotcamp/finhub/common/service/SlackWebhookService.java
src/main/java/fotcamp/finhub/main/controller/SentryController.java
src/main/java/fotcamp/finhub/main/service/MainService.java

[FIN-135] Sentry 에러 로그 Slack 연동

---

Dockerfile

[171]로그인 프로세스 테스트코드 작성

---

Dockerfile

This reverts commit f1ca9e4a496494edca4b9dc57d7d332299f88093.
- 작업1

Revert "[171]로그인 프로세스 테스트코드 작성"
